# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379


social:
  qq:
    appId: 101579347
    appSecret: 8a9ea06c66a32924876410d8936dcbe4
    filterProcessesUrl: /qqLogin
    providerId: callback.do
    signupUrl: /signup

server:
  port: 8080
  servlet:
    session:
      timeout: 600

logging:
  level:
    org.springframework: debug
